[tool:pytest]
testpaths = tests
norecursedirs = .git .tox .pytest_cache
python_files = test_*.py
python_functions = test_*
python_classes = Test*
addopts =
    --strict-markers
    --strict-config
    --disable-warnings
    -p pytest_homeassistant_custom_component
    --asyncio-mode=auto
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
